### ISSUE TITLE
Kein Datepicker im Edit Formular

### ISSUE THREAD

**Issue by swinde** [Wusch/Contao-CalendarEditor#1]
Hallo!

Es wird kein Datumsfeld im Feld Start- & Enddatum ausgegeben. 
In der alten Variante ging das noch.

Steffen Winde

**Comment by Wusch** [comment]
Update ist verfügbar. Die Tabellenstruktur ist dadurch aber weg gefallen.

**Comment by swinde** [comment]
Danke, wer möchte stylt sich das sowieso. Wir könnten auch ein paar CSS Anweisungen hinzufügen.
