### ISSUE TITLE
Modul cal_default-edit.html5

### ISSUE THREAD

**Issue by swinde** [Wusch/Contao-CalendarEditor#2]
Hallo bei der Anzeige des editierbaren Kalenders, wird im body-Tag folgender Code ausgegeben, je nachdem wieviele Kalendereinträge es gibt:

`string(32) "booking-dgh-edit.html?edit=54381" string(32) "booking-dgh-edit.html?edit=54382" string(32) "booking-dgh-edit.html?edit=54382" string(32) "booking-dgh-edit.html?edit=54382" string(32) "booking-dgh-edit.html?edit=54370" string(32) "booking-dgh-edit.html?edit=54370"`

VG Steffen Winde

**Comment by Wusch** [comment]
Fixed
