### ISSUE TITLE
Termin dublizieren fehlerhaft

### ISSUE THREAD

**Issue by swinde** [Wusch/Contao-CalendarEditor#3]
Wenn man einen Termin dubliziert werden nur Start und Enddatum in Schleife angelegt.

**Comment by Wusch** [comment]
Fehler behoben. Sollte jetzt auch funktionieren.

**Comment by swinde** [comment]
Hallo, leider nein! Nach Update hat sich am Verhalten nichts geändert.

**Comment by Wusch** [comment]
Hast du vielleicht einen Screenshot o.ä.?

**Comment by swinde** [comment]
![edit_dublizieren](https://github.com/Wusch/Contao-CalendarEditor/assets/3349884/1d41de8d-0686-4dc6-89b0-1785b3142b7f)
Das setzt sich noch weitere 8 mal fort bis dann Termin speichern kommt. Beim Dublizieren sollte meiner Meinung auch die Daten erhalten bleiben. 
Ich bin leider in Sachen programmieren ein Totalausfall!

**Comment by Wusch** [comment]
Die Daten bleiben erhalten. Du gibts nur die neuen Termine mit Start und Enddatum ein.

**Comment by swinde** [comment]
Okay, jetzt habe ich es verstanden! In einer alten Installation ist das auch so!
Kann geschlossen werden!

**Comment by swinde** [comment]
Ich benutze das hier noch für eine Frage!
Und zwar menatwork/contao-multicolumnwizard ist für Contao 3 gewesen. Man soll https://github.com/menatwork/contao-multicolumnwizard-bundle in Contao 4 benutzen. Vielleicht sollte man das noch anpassen!?
VG Steffen

Wenn Du möchtest erste ich auch noch ein Issue dazu.

**Comment by Wusch** [comment]
Habe es mit angepasst.
